name: Deploy documentation

on:
  release:
    types: [ published ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Build root docs
        run: pnpm docs:build

      - name: Move root docs
        run: |
          mkdir -p site
          cp -r docs/.vitepress/dist/* site

      - name: Build js-core docs
        run: pnpm docs:js-core

      - name: Move js-core docs
        run: |
          mkdir -p site/js-core
          cp -r packages/js-core/docs/.vitepress/dist/* site/js-core

      #      - name: Build vue-core docs
      #        run: pnpm --filter "@petr-ptacek/vue-core" run docs:build
      #
      #      - name: Move vue-core docs
      #        run: cp -r packages/vue-core/docs/.vitepress/dist site/vue-core

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
